### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by schneiderpy** [marberts/piar#5]
There are two License files (LICENSE and LICENSE.md) with the same content, which, in my opinion, makes one superfluous.

Part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/6781)

**Comment by schneiderpy** [comment]
Well, it seems that the final result on the dedicated website depends on the type of license .. For example, the `see` r package changed recently to MIT + file LICENSE while others (including my own pgk `concstats`) use a different type of license (e.g. the `dynamite` package). Maybe @crvernon can help to clarify this.

**Comment by crvernon** [comment]
Yes, it is common to include both in this case because of the way they are read in.  As long as both match (license type and language) you should be OK.  

Thanks!

**Comment by marberts** [comment]
Cool. Both `LICENSE` and `LICENSE.md` agree with each other, so I'm going to close this issue. Thanks.
