### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by schneiderpy** [marberts/piar#9]
Lack of community **guidelines**

> Community guidelines[](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines)
> There should be clear guidelines for third-parties wishing to:
> 
> Contribute to the software
> 
> Report issues or problems with the software
> 
> Seek support

The package might benefit from a _Contributing_ file.

As part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/6781)

**Comment by marberts** [comment]
Thanks for the suggestion. I've added `CONTRIBUTING.md` in [feb6345](https://github.com/marberts/piar/commit/feb63451a522d5ae1b6682fb8766ef9222553bec) with instructions for making contributions, reporting issues/bugs, and seeking support.
